version: '2.1'
services:
  eurekaserver:
    image: docker.io/library/eurekaserver:0.0.1-SNAPSHOT
    container_name: eurekaServer
    ports:
      - "8761:8761"
    networks:
      backend:
        aliases:
          - "eurekaserver"
  configserver:
    image: docker.io/library/configserver:0.0.1-SNAPSHOT
    container_name: configServer
    ports:
       - "8071:8071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "configserver"
  gatewayserver:
    image: docker.io/library/gatewayserver:0.0.1-SNAPSHOT
    container_name: gateway
    ports:
      - "8072:8072"
    networks:
      backend:
        aliases:
          - "gateway"
  base:
    image: docker.io/library/base:0.0.1-SNAPSHOT
    container_name: base
    ports:
      - "8180:8180"
    networks:
      backend:
        aliases:
          - "base"
volumes:
  esdata1:
    driver: local
networks:
  backend:
    driver: bridge