version: '2.1'
services:
  eurekaserver:
    image: docker.io/library/eurekaserver:0.0.1-SNAPSHOT
    container_name: eurekaServer
    ports:
      - "8761:8761"
    networks:
      backend:
        aliases:
          - "eurekaserver"
volumes:
  esdata1:
    driver: local
networks:
  backend:
    driver: bridge